# Generated by Django 5.2 on 2025-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creditcard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mid',
            field=models.IntegerField(default=0),
        ),
    ]
